### ISSUE TITLE
API Request Failed

### ISSUE THREAD

**Issue by muhammad-hunnain786** [Shopify/shopify-app-template-node#1041]
# Issue summary

iam making the shopify app using shopify cli 3.0. all goes well but after installation, the app get crash because of failed api call

i have checked the logs its returning error following error

**Cannot find module '/var/task/node_modules/@shopify/shopify-api/dist/rest-resources/2022-07/index.js**

as in api we are calling this

const { Product } = await import(
    `@shopify/shopify-api/dist/rest-resources/${Shopify.Context.API_VERSION}/index.js`
);

const countData = await Product.count({ session });
res.status(200).send(countData);

## Expected behavior

it should get get the product object and return me the count for of my products

## Specifications

- Browser: chrome
- Device: dell
- Operating System: windows 11

**Comment by mkevinosullivan** [comment]
@muhammad-hunnain786 I'm unable to reproduce this.

Can you share the list of commands you're using to create/run the app? e.g.,
```shell
npm init @shopify/app@latest
cd <app name>
npm run dev
```

Also:
- what directory/folder are you in when you start these commands? (I ask because `/var/task` seems unusual)
- Can you share the output that you see when the error occurs, please?

**Comment by ishefi** [comment]
Happened to me as well, after upgrading from @shopify/app 3.47.3 to 3.49.2
